### ISSUE TITLE
Caught exception while running sniff() [Errno 19] No such device

### ISSUE THREAD

**Issue by JavaRockstar** [NoobieDog/Peanuts#1]
Hi I have been using Snoopy-ng for a while really nice project I always though someone should make a remake of it I try and run the script and return error Caught exception while running sniff() [Errno 19] No such device also I'm calling it from the peanuts.py file. I like how GPS is included I will sure test GPS out later in time the commands I'm using as of now are the basic ones I also tried with wlan1mon incase airmon-ng had put it into monitor mode but i gathered with it being a newer release it would of used iwconfig wlan1 mode monitor to set monitor mode thanks for the hard work.

Edit: I may of spoke to soon re tired the script today and its working perfectly I think my interface was acting up made a script to add monitor mode using iwconfig then launched peanuts and it worked Thanks.

**Comment by NoobieDog** [comment]
ah awesome!, thanks for the feedback. im going to be adding more features as we go along. 

Kind regards
